'''Tests for the initial database schema.

The tests spin up an in‑memory SQLite database, apply the raw SQL migration
script, reflect the tables with SQLAlchemy, and verify that:

1. Both `users` and `students` tables exist.
2. All required columns are present with the correct types.
3. The foreign‑key relationship between `students.user_id` and `users.id`
   is correctly defined.
''' 

import os
import pathlib
import sqlite3
import pytest
from sqlalchemy import create_engine, inspect, Table, MetaData

# Path to the migration script generated by the backend task
MIGRATION_PATH = pathlib.Path(__file__).parents[2] / "migrations" / "20241005_initial_schema.sql"

@pytest.fixture(scope="function")
def connection():
    # Use an in‑memory SQLite database for fast, isolated testing
    engine = create_engine("sqlite:///:memory:")
    conn = engine.connect()
    # Apply the migration script
    with open(MIGRATION_PATH, "r", encoding="utf-8") as f:
        sql = f.read()
    conn.execute(sql)
    yield conn
    conn.close()
    engine.dispose()

def test_tables_exist(connection):
    inspector = inspect(connection)
    tables = inspector.get_table_names()
    assert "users" in tables, "`users` table should be created"
    assert "students" in tables, "`students` table should be created"

def test_users_columns(connection):
    inspector = inspect(connection)
    cols = {c["name"]: c for c in inspector.get_columns("users")}
    expected = {"id", "email", "password_hash", "role"}
    assert expected.issubset(cols.keys()), f"Missing columns in users: {expected - cols.keys()}"
    # Verify constraints
    pk = inspector.get_pk_constraint("users")
    assert pk["constrained_columns"] == ["id"]
    uniques = inspector.get_unique_constraints("users")
    assert any("email" in uc["column_names"] for uc in uniques), "`email` should be unique"

def test_students_columns_and_fk(connection):
    inspector = inspect(connection)
    cols = {c["name"]: c for c in inspector.get_columns("students")}
    expected = {"id", "user_id", "name", "class_name", "enrollment_date"}
    assert expected.issubset(cols.keys()), f"Missing columns in students: {expected - cols.keys()}"
    # Primary key
    pk = inspector.get_pk_constraint("students")
    assert pk["constrained_columns"] == ["id"]
    # Foreign key
    fks = inspector.get_foreign_keys("students")
    assert len(fks) == 1, "students should have exactly one foreign key"
    fk = fks[0]
    assert fk["referred_table"] == "users"
    assert fk["constrained_columns"] == ["user_id"]
    assert fk["referred_columns"] == ["id"]
    # Unique constraint on user_id (one‑to‑one relationship)
    uniques = inspector.get_unique_constraints("students")
    assert any("user_id" in uc["column_names"] for uc in uniques), "`user_id` should be unique"
